@api = http://localhost:5092/api

# @name connexion
POST {{api}}/auth/login
Content-Type: application/json

{ "email": "inspecteur@ct.local", "motDePasse": "Demo123!" }

###
@jeton = {{connexion.response.body.$.jeton}}

GET {{api}}/vehicules?search=AB&page=1
Authorization: Bearer {{jeton}}

###
GET {{api}}/points-controle
Authorization: Bearer {{jeton}}

###
GET {{api}}/controles?statut=Brouillon&mesControles=true
Authorization: Bearer {{jeton}}

###
POST {{api}}/controles
Authorization: Bearer {{jeton}}
Content-Type: application/json

{ "vehiculeId": "<id du véhicule>", "kilometrage": 85000 }
