// <auto-generated />
using System;
using CT.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CT.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CtDbContext))]
    [Migration("20261009061825_ReglementationFrancaise")]
    partial class ReglementationFrancaise
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CT.Domain.Entities.Controle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClotureLe")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ControleInitialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateControle")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateControlePeriodique")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateFinValidite")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateLimiteContreVisite")
                        .HasColumnType("date");

                    b.Property<Guid>("InspecteurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kilometrage")
                        .HasColumnType("int");

                    b.Property<string>("Resultat")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("SynchroniseLe")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VehiculeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ControleInitialId")
                        .IsUnique()
                        .HasFilter("[ControleInitialId] IS NOT NULL");

                    b.HasIndex("DateControle");

                    b.HasIndex("InspecteurId");

                    b.HasIndex("VehiculeId");

                    b.ToTable("Controle", (string)null);
                });

            modelBuilder.Entity("CT.Domain.Entities.Defaillance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("PointControleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PointControleId");

                    b.ToTable("Defaillance", (string)null);
                });

            modelBuilder.Entity("CT.Domain.Entities.Fonction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Fonction", (string)null);
                });

            modelBuilder.Entity("CT.Domain.Entities.PointControle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<Guid>("FonctionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FonctionId");

                    b.ToTable("PointControle", (string)null);
                });

            modelBuilder.Entity("CT.Domain.Entities.Proprietaire", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Nom");

                    b.ToTable("Proprietaire", (string)null);
                });

            modelBuilder.Entity("CT.Domain.Entities.ResultatPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ControleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("PointControleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PointControleId");

                    b.HasIndex("ControleId", "PointControleId")
                        .IsUnique();

                    b.ToTable("ResultatPoint", (string)null);
                });

            modelBuilder.Entity("CT.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateur", (string)null);
                });

            modelBuilder.Entity("CT.Domain.Entities.Vehicule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DatePremiereImmatriculation")
                        .HasColumnType("date");

                    b.Property<string>("Energie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Immatriculation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroChassis")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<Guid>("ProprietaireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeVehicule")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Immatriculation")
                        .IsUnique();

                    b.HasIndex("NumeroChassis")
                        .IsUnique();

                    b.HasIndex("ProprietaireId");

                    b.ToTable("Vehicule", (string)null);
                });

            modelBuilder.Entity("DefaillanceConstatee", b =>
                {
                    b.Property<Guid>("DefaillanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResultatPointId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DefaillanceId", "ResultatPointId");

                    b.HasIndex("ResultatPointId");

                    b.ToTable("DefaillanceConstatee");
                });

            modelBuilder.Entity("CT.Domain.Entities.Controle", b =>
                {
                    b.HasOne("CT.Domain.Entities.Controle", "ControleInitial")
                        .WithOne("ContreVisite")
                        .HasForeignKey("CT.Domain.Entities.Controle", "ControleInitialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CT.Domain.Entities.Utilisateur", "Inspecteur")
                        .WithMany("Controles")
                        .HasForeignKey("InspecteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CT.Domain.Entities.Vehicule", "Vehicule")
                        .WithMany("Controles")
                        .HasForeignKey("VehiculeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ControleInitial");

                    b.Navigation("Inspecteur");

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("CT.Domain.Entities.Defaillance", b =>
                {
                    b.HasOne("CT.Domain.Entities.PointControle", "PointControle")
                        .WithMany("Defaillances")
                        .HasForeignKey("PointControleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PointControle");
                });

            modelBuilder.Entity("CT.Domain.Entities.PointControle", b =>
                {
                    b.HasOne("CT.Domain.Entities.Fonction", "Fonction")
                        .WithMany("Points")
                        .HasForeignKey("FonctionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fonction");
                });

            modelBuilder.Entity("CT.Domain.Entities.ResultatPoint", b =>
                {
                    b.HasOne("CT.Domain.Entities.Controle", "Controle")
                        .WithMany("Resultats")
                        .HasForeignKey("ControleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CT.Domain.Entities.PointControle", "PointControle")
                        .WithMany()
                        .HasForeignKey("PointControleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Controle");

                    b.Navigation("PointControle");
                });

            modelBuilder.Entity("CT.Domain.Entities.Vehicule", b =>
                {
                    b.HasOne("CT.Domain.Entities.Proprietaire", "Proprietaire")
                        .WithMany("Vehicules")
                        .HasForeignKey("ProprietaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proprietaire");
                });

            modelBuilder.Entity("DefaillanceConstatee", b =>
                {
                    b.HasOne("CT.Domain.Entities.Defaillance", null)
                        .WithMany()
                        .HasForeignKey("DefaillanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CT.Domain.Entities.ResultatPoint", null)
                        .WithMany()
                        .HasForeignKey("ResultatPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CT.Domain.Entities.Controle", b =>
                {
                    b.Navigation("ContreVisite");

                    b.Navigation("Resultats");
                });

            modelBuilder.Entity("CT.Domain.Entities.Fonction", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("CT.Domain.Entities.PointControle", b =>
                {
                    b.Navigation("Defaillances");
                });

            modelBuilder.Entity("CT.Domain.Entities.Proprietaire", b =>
                {
                    b.Navigation("Vehicules");
                });

            modelBuilder.Entity("CT.Domain.Entities.Utilisateur", b =>
                {
                    b.Navigation("Controles");
                });

            modelBuilder.Entity("CT.Domain.Entities.Vehicule", b =>
                {
                    b.Navigation("Controles");
                });
#pragma warning restore 612, 618
        }
    }
}
